@dominio = http://localhost:3003
@id = 67eba21db98c883d098bba8d


### Crear usuarios 
POST {{dominio}}/api/v1/usuarios
Content-Type: application/json

{
    "name": "Laura",
    "email": "laura@gmail.com",
    "password": "cande123",
    "username": "Laura94"
}


### Obtener usuarios 
GET {{dominio}}/api/v1/usuarios


### Obtener un usuario 
GET {{dominio}}/api/v1/usuarios/{{id}}

