@dominio = http://localhost:3003
@id = 67fbce0ce015388fbac9f7f7


### Crear usuarios 
POST {{dominio}}/api/v1/usuarios
Content-Type: application/json

{
    "name": "Laura",
    "email": "laura@hotmail.com",
    "password": "laura1233",
    "repeatPassword":"laura1233",
    "username": "Laura94"
}








### Obtener usuarios 
GET {{dominio}}/api/v1/usuarios


### Obtener un usuario 
GET {{dominio}}/api/v1/usuarios/{{id}}



### Registro usuarios 
POST {{dominio}}/api/v1/usuarios/register
Content-Type: application/json

{
    "name": "Administrador",
    "email": "admin@admin.com",
    "password": "admin1994",
    "repeatPassword":"admin1994",
    "username": "adminUploads"
}



### Eliminar un usuario 
DELETE {{dominio}}/api/v1/usuarios/{{id}}





### login usuarios 
POST {{dominio}}/api/v1/usuarios/login
Content-Type: application/json

{
   
    "email": "juan@hotmail.com",
    "password": "juan1233"
   
}





### crear admin 
POST {{dominio}}/api/v1/setup-admin
Content-Type: application/json

{
   "name": "Admin",
   "username": "Admin-SoundsLike",
   "email": "admin@admin.com",
   "password": "contraseñaAdmin123",
  "secretPassword": "clave-soundslike-administrador"
    
   
}